# Generated by Django 5.1.1 on 2025-08-10 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bundling',
            fields=[
                ('id_bundling', models.AutoField(primary_key=True, serialize=False)),
                ('nama_bundling', models.CharField(max_length=255)),
                ('gambar_bundling', models.ImageField(upload_to='static/images/bundling')),
                ('thumbnail_bundling', models.ImageField(blank=True, null=True, upload_to='static/images/thumbnails')),
                ('harga_bundling', models.DecimalField(decimal_places=2, max_digits=10)),
                ('link_shopee', models.URLField(blank=True, null=True, verbose_name='Link Shopee')),
                ('link_tokopedia', models.URLField(blank=True, null=True, verbose_name='Link Tokopedia')),
                ('deskripsi_bundling', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id_kategori', models.AutoField(primary_key=True, serialize=False)),
                ('nama_kategori', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Kegiatan',
            fields=[
                ('id_kegiatan', models.AutoField(primary_key=True, serialize=False)),
                ('nama_kegiatan', models.CharField(max_length=255)),
                ('gambar_kegiatan', models.ImageField(upload_to='static/images/kegiatan')),
                ('deskripsi_kegiatan', models.TextField()),
                ('id_kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kelurahan.kategori')),
            ],
        ),
        migrations.CreateModel(
            name='GambarKegiatan',
            fields=[
                ('id_gambar', models.AutoField(primary_key=True, serialize=False)),
                ('gambar', models.ImageField(upload_to='static/images/kegiatan/additional/')),
                ('keterangan', models.CharField(blank=True, max_length=255, null=True)),
                ('urutan', models.PositiveIntegerField(default=1)),
                ('id_kegiatan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gambar_tambahan', to='kelurahan.kegiatan')),
            ],
            options={
                'ordering': ['urutan'],
            },
        ),
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id_produk', models.AutoField(primary_key=True, serialize=False)),
                ('nama_produk', models.CharField(max_length=255)),
                ('nomor_telepon', models.CharField(max_length=20)),
                ('deskripsi_produk', models.TextField()),
                ('gambar_produk', models.ImageField(upload_to='static/images/produk')),
                ('thumbnail_produk', models.ImageField(blank=True, null=True, upload_to='static/images/thumbnails')),
                ('link_shopee', models.URLField(blank=True, null=True, verbose_name='Link Shopee')),
                ('link_tokopedia', models.URLField(blank=True, null=True, verbose_name='Link Tokopedia')),
                ('harga_produk', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kelurahan.kategori')),
            ],
        ),
        migrations.CreateModel(
            name='DetailBundling',
            fields=[
                ('id_db', models.AutoField(primary_key=True, serialize=False)),
                ('id_bundling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kelurahan.bundling')),
                ('id_produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kelurahan.produk')),
            ],
        ),
    ]
